version: '3'
services:
  app:
    build: .
    environment:
      - RUNNING_IN_DOCKER=true
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"